# -*- coding: utf-8 -*-
"""Acquisition, Chargement et Sauvegarde

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OGUnLzQPhmflTwmFfZPJX3YmwcOXqJyG

#1-Chargement de la vidéo
"""

import cv2
video = cv2.VideoCapture("/content/sample_data/my_video.mp4")

if not video.isOpened():
    print("Error: Could not open video file.")
else:
    print("Video file opened successfully!")

"""#2-Afficher les informations de la vidéo"""

height=video.get(cv2.CAP_PROP_FRAME_HEIGHT)
print(f"La hauteur: {height}")
width=video.get(cv2.CAP_PROP_FRAME_WIDTH)
print(f"La largueur: {width}")
nb_frames=int(video.get(cv2.CAP_PROP_FRAME_COUNT))
print(f"Le nombre de frames: {nb_frames}")
fps=video.get(cv2.CAP_PROP_FPS)
print(f"Le nombre de frame per second: {fps}")

"""#3-Extraction et sauvegarde de frames"""

frame_number =0
saved_count = 0
while video.isOpened():
  ret, frame = video.read()
  if not ret:
    break

  filename= f"/content/frames/frame_{frame_number}.png"
  cv2.imwrite(filename, frame)
  saved_count +=1
  print(f"sauvegarde : {filename}")
  frame_number += 1

print(f"Total frames sauvegardées : {saved_count}")

"""#4-Affichage en continu toutes les 50 ms


"""

import cv2
from google.colab.patches import cv2_imshow
video = cv2.VideoCapture("/content/sample_data/my_video.mp4")
while True:
    ret, frame = video.read()
    if not ret:
        break
    cv2.imshow("Video", frame)
    if cv2.waitKey(50) & 0xFF == ord('q'):
        break

video.release()
cv2.destroyAllWindows()